name: Docker Image CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      run: |
        docker build . --tag docker.pkg.github.com/pablocdixoh/api-poi/poi/web/Dockerfile/api-poi:${{github.sha}}
        docker run docker.pkg.github.com/pablocdixoh/api-poi/api-poi:${{github.sha}}
        docker push docker.pkg.github.com/pablocdixoh/api-poi/api-poi:${{github.sha}}
