name: Docker Image CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      run: |
        echo docker login ghcr.io -u richardopenhack --password-stdin
        docker build . --tag docker.pkg.github.com/PabloCSixOH/api-poi/api-poi:latest
        docker run docker.pkg.github.com/PabloCSixOH/api-poi/api-poi:latest
        docker push docker.pkg.github.com/PabloCSixOH/api-poi/api-poi:latest
