name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        username: pablocsixoh # ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com/pablocsixoh/api-poi/api-poi-docker:${{github.sha}}
        tags: pablocsixoh/api-poi-docker:${{github.sha}}
        repository: /api-poi/
        file: ./poi/web/
        push: true
        pull: true
        
      # added new  
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      # added new
