name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        username: pablocsixoh # ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}  # docker.pkg.github.com
        tags: pablocsixoh/api-poi-docker:${{github.sha}}
        repository: /pablocsixoh/api-poi/
        path: poi/web
        push: true
        pull: true
        
      # added new  
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      # added new
