name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
          image: ${{ github.repository }}/apipoi:${{github.sha}}
          registry: docker.pkg.github.com
          githubOrg: OpenHackEquipo3
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

