name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # set pr number, if it's a pr build
      
      
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com/${{ github.actor }}/${{ github.repository }}/API-POI:${{ github.run_number }}
        tag_with_sha: true
        tag_with_ref: true
        path: poi/web/DockerFile
