name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        path: poi/web
        tags: api-poi, apipoiimage:${{github.sha}}
        push: true

