name: .NET

on:
  push:
    branches: [ main, develop_branch ] 
  pull_request:
    branches:  master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore poi/poi.sln
    - name: Build
      run: dotnet build --no-restore poi/poi.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal poi/poi.sln
