name: .NET

on:
  push:
    branches: [main, develop_branch]
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Restore dependencies
        run: dotnet restore poi/poi.sln
      - name: Build
        run: dotnet build --no-restore poi/poi.sln

        # set pr number, if it's a pr build
      - name: set pr build number
        id: PRNUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3

      - name: Test PR
        run: dotnet test poi/poi.sln --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};" 
        env:
          title: Test Run for PR ${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})"
          file_name: TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md"
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
          name: "Test Run"
          path: ${{github.workspace}}/${{env.file_name}}
        env:
          title: Test Run for PR ${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})"
          file_name: TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md"

      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: ${{env.file_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: Test Run for PR ${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})"
          file_name: TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md"
